version: '3'
services:
  hw:
    container_name: fast_api_app
    build: .
    ports:
      - '5000:5000'
    networks:
      - backend

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB = admin
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    networks:
      - backend
    volumes:
      - ./db/:/var/lib/postgresql/data


networks:
  backend:
    driver: bridge



